---
- name: prep ESX host
  hosts: esx
  vars_files: 
    vars.yml
  tasks: 
  - name: Configure ESXi hostname and public DNS servers
    vmware_dns_config:
      hostname: '{{ esxi_address }}'
      username: '{{ esxi_username }}'
      password: '{{ lab_password }}'
      validate_certs: no 
      change_hostname_to: '{{ esxi_hostname }}'
      domainname: '{{ lab_domain }}'
      dns_servers:
      - '{{ lab_upstream_dns }}'
    delegate_to: localhost
  - name: Download the server ISO
    shell: 'wget -P /vmfs/volumes/{{ esxi_local_datastore }} {{ windows_iso_url }}'
    register: wgetiso
    changed_when: false
    ignore_errors: yes
  - name: Copy floppy.flp to datastore
    copy:
     src: '{{ windows_floppy }}'
     dest: '/vmfs/volumes/{{ esxi_local_datastore }}/floppy.flp'
  - name: Create a virtual machine on given ESXi hostname
    vmware_guest:
      hostname: '{{ esxi_address }}'
      username: '{{ esxi_username }}'
      password: '{{ lab_password }}'
      validate_certs: no 
      folder: /
      name: '{{ dc_hostname }}'
      state: poweredoff
      guest_id: windows9Server64Guest
      cdrom:
        type: iso
        iso_path: '[datastore1] {{ windows_iso }}'
      disk:
      - size_gb: 40
        type: thin
        datastore: datastore1
      hardware:
        memory_mb: 2048
        num_cpus: 2
        scsi: lsilogicsas
      networks:
      - name: VM Network
        device_type: e1000
      wait_for_ip_address: no
    delegate_to: localhost
    register: deploy_vm
  - name: Change virtual machine's boot order and related parameters
    vmware_guest_boot_manager:
      hostname: '{{ esxi_address }}'
      username: '{{ esxi_username }}'
      password: '{{ lab_password }}'
      validate_certs: no 
      name: '{{ dc_hostname }}'
      boot_delay: 1000
      enter_bios_setup: False
      boot_retry_enabled: True
      boot_retry_delay: 22300
      boot_firmware: bios
      secure_boot_enabled: False
      boot_order:
        - cdrom
        - disk
        - ethernet
        - floppy
    delegate_to: localhost
    register: vm_boot_order
  - name: Add a line to a file
    lineinfile:
      path: '/vmfs/volumes/{{ esxi_local_datastore }}/{{ dc_hostname }}/{{ dc_hostname }}.vmx'
      line: 'floppy0.fileType = "file"'
  - name: Add a line to a file
    lineinfile:
      path: '/vmfs/volumes/{{ esxi_local_datastore }}/{{ dc_hostname }}/{{ dc_hostname }}.vmx'
      line: 'floppy0.fileName = "/vmfs/volumes/{{ esxi_local_datastore }}/floppy.flp"'
  - name: Add a line to a file
    lineinfile:
      path: '/vmfs/volumes/{{ esxi_local_datastore }}/{{ dc_hostname }}/{{ dc_hostname }}.vmx'
      line: 'floppy0.present = "FALSE"'
      state: absent
  - name: Set the state of a virtual machine to poweron
    vmware_guest_powerstate:
      hostname: '{{ esxi_address }}'
      username: '{{ esxi_username }}'
      password: '{{ lab_password }}'
      validate_certs: no
      name: '{{ dc_hostname }}'
      state: powered-on
    delegate_to: localhost
    register: powerstate
  - name: Wait for VMware tools to become available by name
    vmware_guest_tools_wait:
      hostname: '{{ esxi_address }}'
      username: '{{ esxi_username }}'
      password: '{{ lab_password }}'
      validate_certs: no
      name: '{{ dc_hostname }}'
    delegate_to: localhost
    register: facts
