--- 
- hosts: localhost 
  name: vCenter Configuration 
  vars:
    validate_certs: no
  vars_files: 
    vars.yml
  tasks: 
  - name: Gather facts about vCenter
    vmware_about_facts:
      hostname: '{{ vcenter_address }}'
      username: '{{ vcenter_username }}'
      password: '{{ lab_password }}'
      validate_certs: '{{ validate_certs }}'
    delegate_to: localhost
    register: vcenter_about_info
  - name: Create Datacenter
    vmware_datacenter:
      hostname: '{{ vcenter_address }}'
      username: '{{ vcenter_username }}'
      password: '{{ lab_password }}'
      datacenter_name: '{{ vcenter_datacenter }}'
      state: present
      validate_certs: '{{ validate_certs }}'
    delegate_to: localhost
  - name: Create Cluster
    vmware_cluster:
      hostname: '{{ vcenter_address }}'
      username: '{{ vcenter_username }}'
      password: '{{ lab_password }}'
      datacenter_name: '{{ vcenter_datacenter }}'
      cluster_name: '{{ vcenter_cluster }}'
      validate_certs: '{{ validate_certs }}'
      enable_ha: no
      enable_drs: yes
      enable_vsan: no
    delegate_to: localhost
  - name: Configure ESXi hostname and private DNS servers
    vmware_dns_config:
      hostname: '{{ esxi_address }}'
      username: '{{ esxi_username }}'
      password: '{{ lab_password }}'
      validate_certs: no 
      change_hostname_to: '{{ esxi_hostname }}'
      domainname: '{{ lab_domain }}'
      dns_servers:
      - '{{ dc_address }}'
    delegate_to: localhost
  - name: Add ESXi Host to vCenter
    vmware_host:
      hostname: '{{ vcenter_address }}'
      username: '{{ vcenter_username }}'
      password: '{{ lab_password }}'
      datacenter: '{{ vcenter_datacenter }}'
      cluster: '{{ vcenter_cluster }}'
      esxi_hostname: '{{ esxi_address }}'
      esxi_username: '{{ esxi_username }}'
      esxi_password: '{{ lab_password }}'
      validate_certs: '{{ validate_certs }}'
      state: present
    delegate_to: localhost
# a brief pause for things to settle
  - name: sleep for 60 seconds and continue with play
    wait_for: timeout=60
    delegate_to: localhost
