--- 
- hosts: localhost 
  gather_facts: false
  name: ESXi Facts 
  vars:
    validate_certs: no
  vars_files: 
    vars.yml
  tasks: 
  # - name: Gather facts about ESXi Host
  #   vmware_host_config_facts:
  #     hostname: '{{ esxi_address }}'
  #     username: '{{ esxi_username }}'
  #     password: '{{ lab_password }}'
  #     esxi_hostname: '{{ esxi_hostname }}'
  #     validate_certs: no
  - name: Wait for vCenter WebServer
    wait_for:
      port: 443
      host: '{{ vcenter_address }}'
      timeout: 300
    connection: local
  - name: Wait for vCenter Service
    wait_for:
      port: 9084
      host: '{{ vcenter_address }}'
      timeout: 300
    connection: local   
