---
- name: Ansible / WinRM / VMware vSphere Guest Tools 
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Enable WinRM to be used with Ansible 
      local_action:
        module: vmware_vm_shell
        hostname: 172.16.108.40
        username: root
        password: "P@ssw0rd" 
        validate_certs: no
        vm_username: Administrator
        vm_password: "P@ssw0rd"
        vm_id: DC01
        vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
        vm_shell_args: "" 
      with_items:
        - '-command "& {Set-ExecutionPolicy Unrestricted}"'
        - '-command "& {Invoke-Expression ((New-Object System.Net.Webclient).DownloadString(\"https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1\"))}"'
      #  - '-command "& {Set-ExecutionPolicy RemoteSigned}"'